// This should be failure because commonjs cannot import ES Module directly.
// import {} from 'option-t/esm/PlainOption/Option';
// import {} from 'option-t/esm/PlainOption/and';
// import {} from 'option-t/esm/PlainOption/andThen';
// import {} from 'option-t/esm/PlainOption/andThenAsync';
// import {} from 'option-t/esm/PlainOption/asMut';
// import {} from 'option-t/esm/PlainOption/compat/v33';
// import {} from 'option-t/esm/PlainOption/drop';
// import {} from 'option-t/esm/PlainOption/equal';
// import {} from 'option-t/esm/PlainOption/expect';
// import {} from 'option-t/esm/PlainOption/filter';
// import {} from 'option-t/esm/PlainOption/flatten';
// import {} from 'option-t/esm/PlainOption/inspect';
// import {} from 'option-t/esm/PlainOption';
// import {} from 'option-t/esm/PlainOption/map';
// import {} from 'option-t/esm/PlainOption/mapAsync';
// import {} from 'option-t/esm/PlainOption/mapOr';
// import {} from 'option-t/esm/PlainOption/mapOrAsync';
// import {} from 'option-t/esm/PlainOption/mapOrElse';
// import {} from 'option-t/esm/PlainOption/mapOrElseAsync';
// import {} from 'option-t/esm/PlainOption/namespace';
// import {} from 'option-t/esm/PlainOption/okOr';
// import {} from 'option-t/esm/PlainOption/okOrElse';
// import {} from 'option-t/esm/PlainOption/or';
// import {} from 'option-t/esm/PlainOption/orElse';
// import {} from 'option-t/esm/PlainOption/orElseAsync';
// import {} from 'option-t/esm/PlainOption/transpose';
// import {} from 'option-t/esm/PlainOption/toNullable';
// import {} from 'option-t/esm/PlainOption/toUndefinable';
// import {} from 'option-t/esm/PlainOption/unwrap';
// import {} from 'option-t/esm/PlainOption/unwrapOr';
// import {} from 'option-t/esm/PlainOption/unwrapOrElse';
// import {} from 'option-t/esm/PlainOption/unwrapOrElseAsync';
// import {} from 'option-t/esm/PlainOption/xor';

import {} from 'option-t/PlainOption';
import {} from 'option-t/PlainOption/and';
import {} from 'option-t/PlainOption/andThen';
import {} from 'option-t/PlainOption/andThenAsync';
import {} from 'option-t/PlainOption/asMut';
import {} from 'option-t/PlainOption/compat/v33';
import {} from 'option-t/PlainOption/drop';
import {} from 'option-t/PlainOption/equal';
import {} from 'option-t/PlainOption/expect';
import {} from 'option-t/PlainOption/filter';
import {} from 'option-t/PlainOption/flatten';
import {} from 'option-t/PlainOption/inspect';
import {} from 'option-t/PlainOption/map';
import {} from 'option-t/PlainOption/mapAsync';
import {} from 'option-t/PlainOption/mapOr';
import {} from 'option-t/PlainOption/mapOrAsync';
import {} from 'option-t/PlainOption/mapOrElse';
import {} from 'option-t/PlainOption/mapOrElseAsync';
import {} from 'option-t/PlainOption/okOr';
import {} from 'option-t/PlainOption/okOrElse';
import {} from 'option-t/PlainOption/Option';
import {} from 'option-t/PlainOption/namespace';
import {} from 'option-t/PlainOption/or';
import {} from 'option-t/PlainOption/orElse';
import {} from 'option-t/PlainOption/orElseAsync';
import {} from 'option-t/PlainOption/transpose';
import {} from 'option-t/PlainOption/toNullable';
import {} from 'option-t/PlainOption/toUndefinable';
import {} from 'option-t/PlainOption/unwrap';
import {} from 'option-t/PlainOption/unwrapOr';
import {} from 'option-t/PlainOption/unwrapOrElse';
import {} from 'option-t/PlainOption/unwrapOrElseAsync';
import {} from 'option-t/PlainOption/xor';
