# https://pnpm.io/pnpm-workspace_yaml
packages:
    - "packages/*"

catalog:
    "@eslint/js": ^9.35.0
    "@reflink/reflink": ^0.1.19
    "@typescript-eslint/eslint-plugin": ^8.42.0
    "@typescript-eslint/parser": ^8.42.0
    ava: ^6.4.1
    del-cli: ^6.0.0
    eslint: ^9.35.0
    eslint-config-prettier: ^10.1.8
    eslint-config-turbo: ^2.5.6
    eslint-plugin-import: ^2.32.0
    expect-type: ^1.2.2
    globals: ^16.4.0
    picomatch: ^4.0.3
    prettier: ^3.6.2
    turbo: ^2.5.6
    typescript: ^5.9.2
