name: Prepare CI
description: This action prepare CI that restore cachable items

inputs:
    node-version:
        required: true

runs:
    using: composite
    steps:
        # Ideally, we run every CI jobs in some containers as a hermetic to make it easy to reproduce the environment locally.
        # However,
        #   1. Recently, it is delayed to update of Node.js' docker image.
        #      This would not be a high impact problem but this is a remarkable problem for major version.
        #      It sometimes 3~4 weeks delay. We cannot test with a new version immidiately.
        #   2. Old actions/setup-node (v1) cannot install the Node.js that is not listed in the action's database.
        #      It's slower than a docker image. See https://github.com/option-t/option-t/pull/681#issuecomment-658219488
        #      But the recent version of its GH action does not such problem.
        #   3. GH Action job is enough to hermetic to achieve, I think. Any fork can them in their forked repository,
        #      and each of steps of them are almost portable to reproduce them for this project's purpose.
        # So we use `actions/setup-node` simply.
        - name: Setup Node.js
          uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
          with:
              node-version: ${{ inputs.node-version }}
              registry-url: "https://registry.npmjs.org"
              # See https://github.com/actions/setup-node/issues/1357
              package-manager-cache: false
        - name: Activate corepack
          shell: bash
          run: | # This workaround https://github.com/nodejs/corepack/issues/612
              npm i -g corepack
              corepack enable
        - name: Get pnpm cache directory
          shell: bash
          id: pnpm-cache-dir
          run: echo "dir=$(pnpm store path)" >> ${GITHUB_OUTPUT}
        - name: Restore dependencies from cache
          id: pnpm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
          uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809
          with:
              path: ${{ steps.pnpm-cache-dir.outputs.dir }}
              key: v0-${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-workspace.yaml') }}
              restore-keys: |
                  v0-${{ runner.os }}-pnpm-
        - name: Install dependencies
          shell: bash
          # We only cache `npm config get cache`, not including `node_modules/`.
          # thus we need to do `npm ci` to restore `node_modules/` so we need run always this step.
          # if: steps.npm-cache.outputs.cache-hit != 'true'
          run: pnpm install
