// This should be failure because commonjs cannot import ES Module directly.
// import {} from 'option-t/esm/Maybe/Maybe';
// import {} from 'option-t/esm/Maybe/and';
// import {} from 'option-t/esm/Maybe/andThen';
// import {} from 'option-t/esm/Maybe/andThenAsync';
// import {} from 'option-t/esm/Maybe/compat/v33';
// import {} from 'option-t/esm/Maybe/expect';
// import {} from 'option-t/esm/Maybe/inspect';
// import {} from 'option-t/esm/Maybe';
// import {} from 'option-t/esm/Maybe/map';
// import {} from 'option-t/esm/Maybe/mapAsync';
// import {} from 'option-t/esm/Maybe/mapOr';
// import {} from 'option-t/esm/Maybe/mapOrAsync';
// import {} from 'option-t/esm/Maybe/mapOrElse';
// import {} from 'option-t/esm/Maybe/mapOrElseAsync';
// import {} from 'option-t/esm/Maybe/namespace';
// import {} from 'option-t/esm/Maybe/okOr';
// import {} from 'option-t/esm/Maybe/okOrElse';
// import {} from 'option-t/esm/Maybe/okOrElseAsync';
// import {} from 'option-t/esm/Maybe/or';
// import {} from 'option-t/esm/Maybe/orElse';
// import {} from 'option-t/esm/Maybe/orElseAsync';
// import {} from 'option-t/esm/Maybe/toNullable';
// import {} from 'option-t/esm/Maybe/toPlainResult';
// import {} from 'option-t/esm/Maybe/toUndefinable';
// import {} from 'option-t/esm/Maybe/unwrap';
// import {} from 'option-t/esm/Maybe/unwrapOr';
// import {} from 'option-t/esm/Maybe/unwrapOrElse';
// import {} from 'option-t/esm/Maybe/unwrapOrElseAsync';
// import {} from 'option-t/esm/Maybe/xor';
// import {} from 'option-t/esm/Maybe/zip';
// import {} from 'option-t/esm/Maybe/zipWith';
// import {} from 'option-t/esm/Maybe/zipWithAsync';

import {} from 'option-t/Maybe';
import {} from 'option-t/Maybe/and';
import {} from 'option-t/Maybe/andThen';
import {} from 'option-t/Maybe/andThenAsync';
import {} from 'option-t/Maybe/compat/v33';
import {} from 'option-t/Maybe/expect';
import {} from 'option-t/Maybe/inspect';
import {} from 'option-t/Maybe/map';
import {} from 'option-t/Maybe/mapAsync';
import {} from 'option-t/Maybe/Maybe';
import {} from 'option-t/Maybe/mapOr';
import {} from 'option-t/Maybe/mapOrAsync';
import {} from 'option-t/Maybe/mapOrElse';
import {} from 'option-t/Maybe/mapOrElseAsync';
import {} from 'option-t/Maybe/namespace';
import {} from 'option-t/Maybe/okOr';
import {} from 'option-t/Maybe/okOrElse';
import {} from 'option-t/Maybe/okOrElseAsync';
import {} from 'option-t/Maybe/or';
import {} from 'option-t/Maybe/orElse';
import {} from 'option-t/Maybe/orElseAsync';
import {} from 'option-t/Maybe/toNullable';
import {} from 'option-t/Maybe/toPlainResult';
import {} from 'option-t/Maybe/toUndefinable';
import {} from 'option-t/Maybe/unwrap';
import {} from 'option-t/Maybe/unwrapOr';
import {} from 'option-t/Maybe/unwrapOrElse';
import {} from 'option-t/Maybe/unwrapOrElseAsync';
import {} from 'option-t/Maybe/xor';
import {} from 'option-t/Maybe/zip';
import {} from 'option-t/Maybe/zipWith';
import {} from 'option-t/Maybe/zipWithAsync';
