import {} from 'option-t/cjs/PlainResult/Result';
import {} from 'option-t/cjs/PlainResult/and';
import {} from 'option-t/cjs/PlainResult/andThen';
import {} from 'option-t/cjs/PlainResult/andThenAsync';
import {} from 'option-t/cjs/PlainResult/asMut';
import {} from 'option-t/cjs/PlainResult/compat/v33';
import {} from 'option-t/cjs/PlainResult/drop';
import {} from 'option-t/cjs/PlainResult/equal';
import {} from 'option-t/cjs/PlainResult/expect';
import {} from 'option-t/cjs/PlainResult/flatten';
import {} from 'option-t/cjs/PlainResult/fromPromiseSettledResult';
import {} from 'option-t/cjs/PlainResult/inspect';
import {} from 'option-t/cjs/PlainResult';
import {} from 'option-t/cjs/PlainResult/map';
import {} from 'option-t/cjs/PlainResult/mapAsync';
import {} from 'option-t/cjs/PlainResult/mapErr';
import {} from 'option-t/cjs/PlainResult/mapErrAsync';
import {} from 'option-t/cjs/PlainResult/mapOr';
import {} from 'option-t/cjs/PlainResult/mapOrAsync';
import {} from 'option-t/cjs/PlainResult/mapOrElse';
import {} from 'option-t/cjs/PlainResult/mapOrElseAsync';
import {} from 'option-t/cjs/PlainResult/namespace';
import {} from 'option-t/cjs/PlainResult/or';
import {} from 'option-t/cjs/PlainResult/orElse';
import {} from 'option-t/cjs/PlainResult/orElseAsync';
import {} from 'option-t/cjs/PlainResult/transpose';
import {} from 'option-t/cjs/PlainResult/toNullable';
import {} from 'option-t/cjs/PlainResult/toOption';
import {} from 'option-t/cjs/PlainResult/toUndefinable';
import {} from 'option-t/cjs/PlainResult/tryCatch';
import {} from 'option-t/cjs/PlainResult/tryCatchAsync';
import {} from 'option-t/cjs/PlainResult/unwrap';
import {} from 'option-t/cjs/PlainResult/unwrapOr';
import {} from 'option-t/cjs/PlainResult/unwrapOrElse';
import {} from 'option-t/cjs/PlainResult/unwrapOrElseAsync';
import {} from 'option-t/cjs/PlainResult/unwrapOrThrowError';

// This should be failure because commonjs cannot import ES Module directly.
// import {} from 'option-t/esm/PlainResult/Result';
// import {} from 'option-t/esm/PlainResult/and';
// import {} from 'option-t/esm/PlainResult/andThen';
// import {} from 'option-t/esm/PlainResult/andThenAsync';
// import {} from 'option-t/esm/PlainResult/asMut';
// import {} from 'option-t/esm/PlainResult/compat/v33';
// import {} from 'option-t/esm/PlainResult/drop';
// import {} from 'option-t/esm/PlainResult/equal';
// import {} from 'option-t/esm/PlainResult/expect';
// import {} from 'option-t/esm/PlainResult/flatten';
// import {} from 'option-t/esm/PlainResult/fromPromiseSettledResult';
// import {} from 'option-t/esm/PlainResult/inspect';
// import {} from 'option-t/esm/PlainResult';
// import {} from 'option-t/esm/PlainResult/map';
// import {} from 'option-t/esm/PlainResult/mapAsync';
// import {} from 'option-t/esm/PlainResult/mapErr';
// import {} from 'option-t/esm/PlainResult/mapErrAsync';
// import {} from 'option-t/esm/PlainResult/mapOr';
// import {} from 'option-t/esm/PlainResult/mapOrAsync';
// import {} from 'option-t/esm/PlainResult/mapOrElse';
// import {} from 'option-t/esm/PlainResult/mapOrElseAsync';
// import {} from 'option-t/esm/PlainResult/namespace';
// import {} from 'option-t/esm/PlainResult/or';
// import {} from 'option-t/esm/PlainResult/orElse';
// import {} from 'option-t/esm/PlainResult/orElseAsync';
// import {} from 'option-t/esm/PlainResult/transpose';
// import {} from 'option-t/esm/PlainResult/toNullable';
// import {} from 'option-t/esm/PlainResult/toOption';
// import {} from 'option-t/esm/PlainResult/toUndefinable';
// import {} from 'option-t/esm/PlainResult/tryCatch';
// import {} from 'option-t/esm/PlainResult/tryCatchAsync';
// import {} from 'option-t/esm/PlainResult/unwrap';
// import {} from 'option-t/esm/PlainResult/unwrapOr';
// import {} from 'option-t/esm/PlainResult/unwrapOrElse';
// import {} from 'option-t/esm/PlainResult/unwrapOrElseAsync';
// import {} from 'option-t/esm/PlainResult/unwrapOrThrowError';

import {} from 'option-t/lib/PlainResult/Result';
import {} from 'option-t/lib/PlainResult/and';
import {} from 'option-t/lib/PlainResult/andThen';
import {} from 'option-t/lib/PlainResult/andThenAsync';
import {} from 'option-t/lib/PlainResult/asMut';
import {} from 'option-t/lib/PlainResult/compat/v33';
import {} from 'option-t/lib/PlainResult/drop';
import {} from 'option-t/lib/PlainResult/equal';
import {} from 'option-t/lib/PlainResult/expect';
import {} from 'option-t/lib/PlainResult/flatten';
import {} from 'option-t/lib/PlainResult/fromPromiseSettledResult';
import {} from 'option-t/lib/PlainResult/inspect';
import {} from 'option-t/lib/PlainResult';
import {} from 'option-t/lib/PlainResult/map';
import {} from 'option-t/lib/PlainResult/mapAsync';
import {} from 'option-t/lib/PlainResult/mapErr';
import {} from 'option-t/lib/PlainResult/mapErrAsync';
import {} from 'option-t/lib/PlainResult/mapOr';
import {} from 'option-t/lib/PlainResult/mapOrAsync';
import {} from 'option-t/lib/PlainResult/mapOrElse';
import {} from 'option-t/lib/PlainResult/mapOrElseAsync';
import {} from 'option-t/lib/PlainResult/namespace';
import {} from 'option-t/lib/PlainResult/or';
import {} from 'option-t/lib/PlainResult/orElse';
import {} from 'option-t/lib/PlainResult/orElseAsync';
import {} from 'option-t/lib/PlainResult/transpose';
import {} from 'option-t/lib/PlainResult/toNullable';
import {} from 'option-t/lib/PlainResult/toOption';
import {} from 'option-t/lib/PlainResult/toUndefinable';
import {} from 'option-t/lib/PlainResult/tryCatch';
import {} from 'option-t/lib/PlainResult/tryCatchAsync';
import {} from 'option-t/lib/PlainResult/unwrap';
import {} from 'option-t/lib/PlainResult/unwrapOr';
import {} from 'option-t/lib/PlainResult/unwrapOrElse';
import {} from 'option-t/lib/PlainResult/unwrapOrElseAsync';
import {} from 'option-t/lib/PlainResult/unwrapOrThrowError';

import {} from 'option-t/PlainResult';
import {} from 'option-t/PlainResult/and';
import {} from 'option-t/PlainResult/andThen';
import {} from 'option-t/PlainResult/andThenAsync';
import {} from 'option-t/PlainResult/asMut';
import {} from 'option-t/PlainResult/compat/v33';
import {} from 'option-t/PlainResult/drop';
import {} from 'option-t/PlainResult/equal';
import {} from 'option-t/PlainResult/expect';
import {} from 'option-t/PlainResult/flatten';
import {} from 'option-t/PlainResult/fromPromiseSettledResult';
import {} from 'option-t/PlainResult/inspect';
import {} from 'option-t/PlainResult/map';
import {} from 'option-t/PlainResult/mapAsync';
import {} from 'option-t/PlainResult/mapErr';
import {} from 'option-t/PlainResult/mapErrAsync';
import {} from 'option-t/PlainResult/mapOr';
import {} from 'option-t/PlainResult/mapOrAsync';
import {} from 'option-t/PlainResult/mapOrElse';
import {} from 'option-t/PlainResult/mapOrElseAsync';
import {} from 'option-t/PlainResult/namespace';
import {} from 'option-t/PlainResult/or';
import {} from 'option-t/PlainResult/orElse';
import {} from 'option-t/PlainResult/orElseAsync';
import {} from 'option-t/PlainResult/Result';
import {} from 'option-t/PlainResult/toNullable';
import {} from 'option-t/PlainResult/toOption';
import {} from 'option-t/PlainResult/toUndefinable';
import {} from 'option-t/PlainResult/tryCatch';
import {} from 'option-t/PlainResult/tryCatchAsync';
import {} from 'option-t/PlainResult/transpose';
import {} from 'option-t/PlainResult/unwrap';
import {} from 'option-t/PlainResult/unwrapOr';
import {} from 'option-t/PlainResult/unwrapOrElse';
import {} from 'option-t/PlainResult/unwrapOrElseAsync';
import {} from 'option-t/PlainResult/unwrapOrThrowError';
