/* eslint sort-keys: ["error", "asc", { caseSensitive: true }] */

import test from 'ava';
import { testImportExposedPath } from './helper.mjs';

testImportExposedPath(
    test,
    Object.keys({
        './Maybe': null,
        './Maybe/Maybe': null,
        './Maybe/and': null,
        './Maybe/andThen': null,
        './Maybe/andThenAsync': null,
        './Maybe/filter': null,
        './Maybe/filterAsync': null,
        './Maybe/inspect': null,
        './Maybe/map': null,
        './Maybe/mapAsync': null,
        './Maybe/mapOr': null,
        './Maybe/mapOrAsync': null,
        './Maybe/mapOrElse': null,
        './Maybe/mapOrElseAsync': null,
        './Maybe/namespace': null,
        './Maybe/okOr': null,
        './Maybe/okOrElse': null,
        './Maybe/okOrElseAsync': null,
        './Maybe/or': null,
        './Maybe/orElse': null,
        './Maybe/orElseAsync': null,
        './Maybe/toNullable': null,
        './Maybe/toPlainResult': null,
        './Maybe/toUndefinable': null,
        './Maybe/unwrapOr': null,
        './Maybe/unwrapOrElse': null,
        './Maybe/unwrapOrElseAsync': null,
        './Maybe/xor': null,
        './Maybe/zip': null,
        './Maybe/zipWith': null,

        './maybe': null,
        './maybe/and': null,
        './maybe/and_then': null,
        './maybe/and_then_async': null,
        './maybe/filter': null,
        './maybe/filter_async': null,
        './maybe/inspect': null,
        './maybe/map': null,
        './maybe/map_async': null,
        './maybe/map_or': null,
        './maybe/map_or_async': null,
        './maybe/map_or_else': null,
        './maybe/map_or_else_async': null,
        './maybe/maybe': null,
        './maybe/namespace': null,
        './maybe/ok_or': null,
        './maybe/ok_or_else': null,
        './maybe/ok_or_else_async': null,
        './maybe/or': null,
        './maybe/or_else': null,
        './maybe/or_else_async': null,
        './maybe/to_nullable': null,
        './maybe/to_plain_result': null,
        './maybe/to_undefinable': null,
        './maybe/unwrap_or': null,
        './maybe/unwrap_or_else': null,
        './maybe/unwrap_or_else_async': null,
        './maybe/xor': null,
        './maybe/zip': null,
        './maybe/zip_with': null,
    }),
);
