/* eslint sort-keys: ["error", "asc", { caseSensitive: true }] */

import test from 'ava';
import { testImportExposedPath } from './helper.mjs';

testImportExposedPath(
    test,
    Object.keys({
        './PlainOption': null,
        './PlainOption/Option': null,
        './PlainOption/and': null,
        './PlainOption/andThen': null,
        './PlainOption/andThenAsync': null,
        './PlainOption/asMut': null,
        './PlainOption/drop': null,
        './PlainOption/equal': null,
        './PlainOption/filter': null,
        './PlainOption/flatten': null,
        './PlainOption/fromResult': null,
        './PlainOption/inspect': null,
        './PlainOption/map': null,
        './PlainOption/mapAsync': null,
        './PlainOption/mapOr': null,
        './PlainOption/mapOrAsync': null,
        './PlainOption/mapOrElse': null,
        './PlainOption/mapOrElseAsync': null,
        './PlainOption/namespace': null,
        './PlainOption/okOr': null,
        './PlainOption/okOrElse': null,
        './PlainOption/or': null,
        './PlainOption/orElse': null,
        './PlainOption/orElseAsync': null,
        './PlainOption/toNullable': null,
        './PlainOption/toUndefinable': null,
        './PlainOption/transpose': null,
        './PlainOption/unwrapOr': null,
        './PlainOption/unwrapOrElse': null,
        './PlainOption/unwrapOrElseAsync': null,
        './PlainOption/xor': null,

        './plain_option': null,
        './plain_option/and': null,
        './plain_option/and_then': null,
        './plain_option/and_then_async': null,
        './plain_option/as_mut': null,
        './plain_option/drop': null,
        './plain_option/equal': null,
        './plain_option/filter': null,
        './plain_option/flatten': null,
        './plain_option/from_result': null,
        './plain_option/inspect': null,
        './plain_option/map': null,
        './plain_option/map_async': null,
        './plain_option/map_or': null,
        './plain_option/map_or_async': null,
        './plain_option/map_or_else': null,
        './plain_option/map_or_else_async': null,
        './plain_option/namespace': null,
        './plain_option/ok_or': null,
        './plain_option/ok_or_else': null,
        './plain_option/option': null,
        './plain_option/or': null,
        './plain_option/or_else': null,
        './plain_option/or_else_async': null,
        './plain_option/to_nullable': null,
        './plain_option/to_undefinable': null,
        './plain_option/transpose': null,
        './plain_option/unwrap_or': null,
        './plain_option/unwrap_or_else': null,
        './plain_option/unwrap_or_else_async': null,
        './plain_option/xor': null,
    }),
);
