/* eslint sort-keys: ["error", "asc", { caseSensitive: true }] */

import test from 'ava';
import { testImportExposedPath } from './helper.mjs';

testImportExposedPath(
    test,
    Object.keys({
        './Undefinable': null,
        './Undefinable/Undefinable': null,
        './Undefinable/and': null,
        './Undefinable/andThen': null,
        './Undefinable/andThenAsync': null,
        './Undefinable/filter': null,
        './Undefinable/filterAsync': null,
        './Undefinable/inspect': null,
        './Undefinable/map': null,
        './Undefinable/mapAsync': null,
        './Undefinable/mapOr': null,
        './Undefinable/mapOrAsync': null,
        './Undefinable/mapOrElse': null,
        './Undefinable/mapOrElseAsync': null,
        './Undefinable/namespace': null,
        './Undefinable/okOr': null,
        './Undefinable/okOrElse': null,
        './Undefinable/okOrElseAsync': null,
        './Undefinable/or': null,
        './Undefinable/orElse': null,
        './Undefinable/orElseAsync': null,
        './Undefinable/toNullable': null,
        './Undefinable/toPlainResult': null,
        './Undefinable/unwrapOr': null,
        './Undefinable/unwrapOrElse': null,
        './Undefinable/unwrapOrElseAsync': null,
        './Undefinable/xor': null,
        './Undefinable/zip': null,
        './Undefinable/zipWith': null,
        './Undefinable/zipWithAsync': null,

        './undefinable': null,
        './undefinable/and': null,
        './undefinable/and_then': null,
        './undefinable/and_then_async': null,
        './undefinable/filter': null,
        './undefinable/filter_async': null,
        './undefinable/inspect': null,
        './undefinable/map': null,
        './undefinable/map_async': null,
        './undefinable/map_or': null,
        './undefinable/map_or_async': null,
        './undefinable/map_or_else': null,
        './undefinable/map_or_else_async': null,
        './undefinable/namespace': null,
        './undefinable/ok_or': null,
        './undefinable/ok_or_else': null,
        './undefinable/ok_or_else_async': null,
        './undefinable/or': null,
        './undefinable/or_else': null,
        './undefinable/or_else_async': null,
        './undefinable/to_nullable': null,
        './undefinable/to_plain_result': null,
        './undefinable/undefinable': null,
        './undefinable/unwrap_or': null,
        './undefinable/unwrap_or_else': null,
        './undefinable/unwrap_or_else_async': null,
        './undefinable/xor': null,
        './undefinable/zip': null,
        './undefinable/zip_with': null,
        './undefinable/zip_with_async': null,
    }),
);
