/* eslint sort-keys: ["error", "asc", { caseSensitive: true }] */
import {
    pathRedirectionTo,
    pathRedirectionForLegacy,
    pathRedirectionForRoot,
    pathExperimentalAndHidden,
} from './api_path_descriptor.mjs';

const MAYBE_DIR = 'maybe';
const NULLABLE_DIR = 'nullable';
const UNDEFINABLE_DIR = 'undefinable';
const PLAIN_OPTION_DIR = 'plain_option';
const PLAIN_RESULT_DIR = 'plain_result';

export const apiTable = Object.freeze({
    '.': pathRedirectionForRoot('index'),

    'ClassicOption': pathRedirectionForLegacy('classic_option/index'),
    'ClassicResult': pathRedirectionForLegacy('classic_result/index'),

    'Maybe': pathRedirectionTo(`${MAYBE_DIR}/index`),
    'Maybe/Maybe': pathRedirectionTo(`${MAYBE_DIR}/maybe`),
    'Maybe/and': pathRedirectionTo(`${MAYBE_DIR}/and`),
    'Maybe/andThen': pathRedirectionTo(`${MAYBE_DIR}/and_then`),
    'Maybe/andThenAsync': pathRedirectionTo(`${MAYBE_DIR}/and_then_async`),
    'Maybe/filter': pathRedirectionTo(`${MAYBE_DIR}/filter`),
    'Maybe/filterAsync': pathRedirectionTo(`${MAYBE_DIR}/filter_async`),
    'Maybe/inspect': pathRedirectionTo(`${MAYBE_DIR}/inspect`),
    'Maybe/map': pathRedirectionTo(`${MAYBE_DIR}/map`),
    'Maybe/mapAsync': pathRedirectionTo(`${MAYBE_DIR}/map_async`),
    'Maybe/mapOr': pathRedirectionTo(`${MAYBE_DIR}/map_or`),
    'Maybe/mapOrAsync': pathRedirectionTo(`${MAYBE_DIR}/map_or_async`),
    'Maybe/mapOrElse': pathRedirectionTo(`${MAYBE_DIR}/map_or_else`),
    'Maybe/mapOrElseAsync': pathRedirectionTo(`${MAYBE_DIR}/map_or_else_async`),
    'Maybe/namespace': pathRedirectionTo(`${MAYBE_DIR}/namespace`),
    'Maybe/okOr': pathRedirectionTo(`${MAYBE_DIR}/ok_or`),
    'Maybe/okOrElse': pathRedirectionTo(`${MAYBE_DIR}/ok_or_else`),
    'Maybe/okOrElseAsync': pathRedirectionTo(`${MAYBE_DIR}/ok_or_else_async`),
    'Maybe/or': pathRedirectionTo(`${MAYBE_DIR}/or`),
    'Maybe/orElse': pathRedirectionTo(`${MAYBE_DIR}/or_else`),
    'Maybe/orElseAsync': pathRedirectionTo(`${MAYBE_DIR}/or_else_async`),
    'Maybe/toNullable': pathRedirectionTo(`${MAYBE_DIR}/to_nullable`),
    'Maybe/toPlainResult': pathRedirectionTo(`${MAYBE_DIR}/to_plain_result`),
    'Maybe/toUndefinable': pathRedirectionTo(`${MAYBE_DIR}/to_undefinable`),
    'Maybe/unwrapOr': pathRedirectionTo(`${MAYBE_DIR}/unwrap_or`),
    'Maybe/unwrapOrElse': pathRedirectionTo(`${MAYBE_DIR}/unwrap_or_else`),
    'Maybe/unwrapOrElseAsync': pathRedirectionTo(`${MAYBE_DIR}/unwrap_or_else_async`),
    'Maybe/xor': pathRedirectionTo(`${MAYBE_DIR}/xor`),
    'Maybe/zip': pathRedirectionTo(`${MAYBE_DIR}/zip`),
    'Maybe/zipWith': pathRedirectionTo(`${MAYBE_DIR}/zip_with`),
    'Maybe/zipWithAsync': pathRedirectionTo(`${MAYBE_DIR}/zip_with_async`),

    'Nullable': pathRedirectionTo(`${NULLABLE_DIR}/index`),
    'Nullable/Nullable': pathRedirectionTo(`${NULLABLE_DIR}/nullable`),
    'Nullable/and': pathRedirectionTo(`${NULLABLE_DIR}/and`),
    'Nullable/andThen': pathRedirectionTo(`${NULLABLE_DIR}/and_then`),
    'Nullable/andThenAsync': pathRedirectionTo(`${NULLABLE_DIR}/and_then_async`),
    'Nullable/filter': pathRedirectionTo(`${NULLABLE_DIR}/filter`),
    'Nullable/filterAsync': pathRedirectionTo(`${NULLABLE_DIR}/filter_async`),
    'Nullable/inspect': pathRedirectionTo(`${NULLABLE_DIR}/inspect`),
    'Nullable/map': pathRedirectionTo(`${NULLABLE_DIR}/map`),
    'Nullable/mapAsync': pathRedirectionTo(`${NULLABLE_DIR}/map_async`),
    'Nullable/mapOr': pathRedirectionTo(`${NULLABLE_DIR}/map_or`),
    'Nullable/mapOrAsync': pathRedirectionTo(`${NULLABLE_DIR}/map_or_async`),
    'Nullable/mapOrElse': pathRedirectionTo(`${NULLABLE_DIR}/map_or_else`),
    'Nullable/mapOrElseAsync': pathRedirectionTo(`${NULLABLE_DIR}/map_or_else_async`),
    'Nullable/namespace': pathRedirectionTo(`${NULLABLE_DIR}/namespace`),
    'Nullable/okOr': pathRedirectionTo(`${NULLABLE_DIR}/ok_or`),
    'Nullable/okOrElse': pathRedirectionTo(`${NULLABLE_DIR}/ok_or_else`),
    'Nullable/okOrElseAsync': pathRedirectionTo(`${NULLABLE_DIR}/ok_or_else_async`),
    'Nullable/or': pathRedirectionTo(`${NULLABLE_DIR}/or`),
    'Nullable/orElse': pathRedirectionTo(`${NULLABLE_DIR}/or_else`),
    'Nullable/orElseAsync': pathRedirectionTo(`${NULLABLE_DIR}/or_else_async`),
    'Nullable/toPlainResult': pathRedirectionTo(`${NULLABLE_DIR}/to_plain_result`),
    'Nullable/toUndefinable': pathRedirectionTo(`${NULLABLE_DIR}/to_undefinable`),
    'Nullable/unwrapOr': pathRedirectionTo(`${NULLABLE_DIR}/unwrap_or`),
    'Nullable/unwrapOrElse': pathRedirectionTo(`${NULLABLE_DIR}/unwrap_or_else`),
    'Nullable/unwrapOrElseAsync': pathRedirectionTo(`${NULLABLE_DIR}/unwrap_or_else_async`),
    'Nullable/xor': pathRedirectionTo(`${NULLABLE_DIR}/xor`),
    'Nullable/zip': pathRedirectionTo(`${NULLABLE_DIR}/zip`),
    'Nullable/zipWith': pathRedirectionTo(`${NULLABLE_DIR}/zip_with`),
    'Nullable/zipWithAsync': pathRedirectionTo(`${NULLABLE_DIR}/zip_with_async`),

    'PlainOption': pathRedirectionTo(`${PLAIN_OPTION_DIR}/index`),
    'PlainOption/Option': pathRedirectionTo(`${PLAIN_OPTION_DIR}/option`),
    'PlainOption/and': pathRedirectionTo(`${PLAIN_OPTION_DIR}/and`),
    'PlainOption/andThen': pathRedirectionTo(`${PLAIN_OPTION_DIR}/and_then`),
    'PlainOption/andThenAsync': pathRedirectionTo(`${PLAIN_OPTION_DIR}/and_then_async`),
    'PlainOption/asMut': pathRedirectionTo(`${PLAIN_OPTION_DIR}/as_mut`),
    'PlainOption/drop': pathRedirectionTo(`${PLAIN_OPTION_DIR}/drop`),
    'PlainOption/equal': pathRedirectionTo(`${PLAIN_OPTION_DIR}/equal`),
    'PlainOption/filter': pathRedirectionTo(`${PLAIN_OPTION_DIR}/filter`),
    'PlainOption/flatten': pathRedirectionTo(`${PLAIN_OPTION_DIR}/flatten`),
    'PlainOption/fromResult': pathRedirectionTo(`${PLAIN_OPTION_DIR}/from_result`),
    'PlainOption/inspect': pathRedirectionTo(`${PLAIN_OPTION_DIR}/inspect`),
    'PlainOption/map': pathRedirectionTo(`${PLAIN_OPTION_DIR}/map`),
    'PlainOption/mapAsync': pathRedirectionTo(`${PLAIN_OPTION_DIR}/map_async`),
    'PlainOption/mapOr': pathRedirectionTo(`${PLAIN_OPTION_DIR}/map_or`),
    'PlainOption/mapOrAsync': pathRedirectionTo(`${PLAIN_OPTION_DIR}/map_or_async`),
    'PlainOption/mapOrElse': pathRedirectionTo(`${PLAIN_OPTION_DIR}/map_or_else`),
    'PlainOption/mapOrElseAsync': pathRedirectionTo(`${PLAIN_OPTION_DIR}/map_or_else_async`),
    'PlainOption/namespace': pathRedirectionTo(`${PLAIN_OPTION_DIR}/namespace`),
    'PlainOption/okOr': pathRedirectionTo(`${PLAIN_OPTION_DIR}/ok_or`),
    'PlainOption/okOrElse': pathRedirectionTo(`${PLAIN_OPTION_DIR}/ok_or_else`),
    'PlainOption/or': pathRedirectionTo(`${PLAIN_OPTION_DIR}/or`),
    'PlainOption/orElse': pathRedirectionTo(`${PLAIN_OPTION_DIR}/or_else`),
    'PlainOption/orElseAsync': pathRedirectionTo(`${PLAIN_OPTION_DIR}/or_else_async`),
    'PlainOption/toNullable': pathRedirectionTo(`${PLAIN_OPTION_DIR}/to_nullable`),
    'PlainOption/toUndefinable': pathRedirectionTo(`${PLAIN_OPTION_DIR}/to_undefinable`),
    'PlainOption/transpose': pathRedirectionTo(`${PLAIN_OPTION_DIR}/transpose`),
    'PlainOption/unwrapOr': pathRedirectionTo(`${PLAIN_OPTION_DIR}/unwrap_or`),
    'PlainOption/unwrapOrElse': pathRedirectionTo(`${PLAIN_OPTION_DIR}/unwrap_or_else`),
    'PlainOption/unwrapOrElseAsync': pathRedirectionTo(`${PLAIN_OPTION_DIR}/unwrap_or_else_async`),
    'PlainOption/xor': pathRedirectionTo(`${PLAIN_OPTION_DIR}/xor`),

    'PlainResult': pathRedirectionTo(`${PLAIN_RESULT_DIR}/index`),
    'PlainResult/Result': pathRedirectionTo(`${PLAIN_RESULT_DIR}/result`),
    'PlainResult/and': pathRedirectionTo(`${PLAIN_RESULT_DIR}/and`),
    'PlainResult/andThen': pathRedirectionTo(`${PLAIN_RESULT_DIR}/and_then`),
    'PlainResult/andThenAsync': pathRedirectionTo(`${PLAIN_RESULT_DIR}/and_then_async`),
    'PlainResult/asMut': pathRedirectionTo(`${PLAIN_RESULT_DIR}/as_mut`),
    'PlainResult/drop': pathRedirectionTo(`${PLAIN_RESULT_DIR}/drop`),
    'PlainResult/equal': pathRedirectionTo(`${PLAIN_RESULT_DIR}/equal`),
    'PlainResult/flatten': pathRedirectionTo(`${PLAIN_RESULT_DIR}/flatten`),
    'PlainResult/fromPromiseSettledResult': pathRedirectionTo(
        'plain_result/from_promise_settled_result',
    ),
    'PlainResult/inspect': pathRedirectionTo(`${PLAIN_RESULT_DIR}/inspect`),
    'PlainResult/isErrAnd': pathRedirectionTo(`${PLAIN_RESULT_DIR}/is_err_and`),
    'PlainResult/isOkAnd': pathRedirectionTo(`${PLAIN_RESULT_DIR}/is_ok_and`),
    'PlainResult/map': pathRedirectionTo(`${PLAIN_RESULT_DIR}/map`),
    'PlainResult/mapAsync': pathRedirectionTo(`${PLAIN_RESULT_DIR}/map_async`),
    'PlainResult/mapErr': pathRedirectionTo(`${PLAIN_RESULT_DIR}/map_err`),
    'PlainResult/mapErrAsync': pathRedirectionTo(`${PLAIN_RESULT_DIR}/map_err_async`),
    'PlainResult/mapOr': pathRedirectionTo(`${PLAIN_RESULT_DIR}/map_or`),
    'PlainResult/mapOrAsync': pathRedirectionTo(`${PLAIN_RESULT_DIR}/map_or_async`),
    'PlainResult/mapOrElse': pathRedirectionTo(`${PLAIN_RESULT_DIR}/map_or_else`),
    'PlainResult/mapOrElseAsync': pathRedirectionTo(`${PLAIN_RESULT_DIR}/map_or_else_async`),
    'PlainResult/namespace': pathRedirectionTo(`${PLAIN_RESULT_DIR}/namespace`),
    'PlainResult/or': pathRedirectionTo(`${PLAIN_RESULT_DIR}/or`),
    'PlainResult/orElse': pathRedirectionTo(`${PLAIN_RESULT_DIR}/or_else`),
    'PlainResult/orElseAsync': pathRedirectionTo(`${PLAIN_RESULT_DIR}/or_else_async`),
    'PlainResult/toNullable': pathRedirectionTo(`${PLAIN_RESULT_DIR}/to_nullable`),
    'PlainResult/toUndefinable': pathRedirectionTo(`${PLAIN_RESULT_DIR}/to_undefinable`),
    'PlainResult/transpose': pathRedirectionTo(`${PLAIN_RESULT_DIR}/transpose`),
    'PlainResult/tryCatch': pathRedirectionTo(`${PLAIN_RESULT_DIR}/try_catch`),
    'PlainResult/tryCatchAsync': pathRedirectionTo(`${PLAIN_RESULT_DIR}/try_catch_async`),
    'PlainResult/unwrapOr': pathRedirectionTo(`${PLAIN_RESULT_DIR}/unwrap_or`),
    'PlainResult/unwrapOrElse': pathRedirectionTo(`${PLAIN_RESULT_DIR}/unwrap_or_else`),
    'PlainResult/unwrapOrElseAsync': pathRedirectionTo(`${PLAIN_RESULT_DIR}/unwrap_or_else_async`),
    'PlainResult/unwrapOrThrowError': pathRedirectionTo(
        `${PLAIN_RESULT_DIR}/unwrap_or_throw_error`,
    ),

    'Undefinable': pathRedirectionTo(`${UNDEFINABLE_DIR}/index`),
    'Undefinable/Undefinable': pathRedirectionTo(`${UNDEFINABLE_DIR}/undefinable`),
    'Undefinable/and': pathRedirectionTo(`${UNDEFINABLE_DIR}/and`),
    'Undefinable/andThen': pathRedirectionTo(`${UNDEFINABLE_DIR}/and_then`),
    'Undefinable/andThenAsync': pathRedirectionTo(`${UNDEFINABLE_DIR}/and_then_async`),
    'Undefinable/filter': pathRedirectionTo(`${UNDEFINABLE_DIR}/filter`),
    'Undefinable/filterAsync': pathRedirectionTo(`${UNDEFINABLE_DIR}/filter_async`),
    'Undefinable/inspect': pathRedirectionTo(`${UNDEFINABLE_DIR}/inspect`),
    'Undefinable/map': pathRedirectionTo(`${UNDEFINABLE_DIR}/map`),
    'Undefinable/mapAsync': pathRedirectionTo(`${UNDEFINABLE_DIR}/map_async`),
    'Undefinable/mapOr': pathRedirectionTo(`${UNDEFINABLE_DIR}/map_or`),
    'Undefinable/mapOrAsync': pathRedirectionTo(`${UNDEFINABLE_DIR}/map_or_async`),
    'Undefinable/mapOrElse': pathRedirectionTo(`${UNDEFINABLE_DIR}/map_or_else`),
    'Undefinable/mapOrElseAsync': pathRedirectionTo(`${UNDEFINABLE_DIR}/map_or_else_async`),
    'Undefinable/namespace': pathRedirectionTo(`${UNDEFINABLE_DIR}/namespace`),
    'Undefinable/okOr': pathRedirectionTo(`${UNDEFINABLE_DIR}/ok_or`),
    'Undefinable/okOrElse': pathRedirectionTo(`${UNDEFINABLE_DIR}/ok_or_else`),
    'Undefinable/okOrElseAsync': pathRedirectionTo(`${UNDEFINABLE_DIR}/ok_or_else_async`),
    'Undefinable/or': pathRedirectionTo(`${UNDEFINABLE_DIR}/or`),
    'Undefinable/orElse': pathRedirectionTo(`${UNDEFINABLE_DIR}/or_else`),
    'Undefinable/orElseAsync': pathRedirectionTo(`${UNDEFINABLE_DIR}/or_else_async`),
    'Undefinable/toNullable': pathRedirectionTo(`${UNDEFINABLE_DIR}/to_nullable`),
    'Undefinable/toPlainResult': pathRedirectionTo(`${UNDEFINABLE_DIR}/to_plain_result`),
    'Undefinable/unwrapOr': pathRedirectionTo(`${UNDEFINABLE_DIR}/unwrap_or`),
    'Undefinable/unwrapOrElse': pathRedirectionTo(`${UNDEFINABLE_DIR}/unwrap_or_else`),
    'Undefinable/unwrapOrElseAsync': pathRedirectionTo(`${UNDEFINABLE_DIR}/unwrap_or_else_async`),
    'Undefinable/xor': pathRedirectionTo(`${UNDEFINABLE_DIR}/xor`),
    'Undefinable/zip': pathRedirectionTo(`${UNDEFINABLE_DIR}/zip`),
    'Undefinable/zipWith': pathRedirectionTo(`${UNDEFINABLE_DIR}/zip_with`),
    'Undefinable/zipWithAsync': pathRedirectionTo(`${UNDEFINABLE_DIR}/zip_with_async`),

    'classic_option': pathExperimentalAndHidden('classic_option/index'),
    'classic_result': pathExperimentalAndHidden('classic_result/index'),

    'maybe': pathExperimentalAndHidden(`${MAYBE_DIR}/index`),
    'maybe/and': pathExperimentalAndHidden(`${MAYBE_DIR}/and`),
    'maybe/and_then': pathExperimentalAndHidden(`${MAYBE_DIR}/and_then`),
    'maybe/and_then_async': pathExperimentalAndHidden(`${MAYBE_DIR}/and_then_async`),
    'maybe/filter': pathExperimentalAndHidden(`${MAYBE_DIR}/filter`),
    'maybe/filter_async': pathExperimentalAndHidden(`${MAYBE_DIR}/filter_async`),
    'maybe/inspect': pathExperimentalAndHidden(`${MAYBE_DIR}/inspect`),
    'maybe/map': pathExperimentalAndHidden(`${MAYBE_DIR}/map`),
    'maybe/map_async': pathExperimentalAndHidden(`${MAYBE_DIR}/map_async`),
    'maybe/map_or': pathExperimentalAndHidden(`${MAYBE_DIR}/map_or`),
    'maybe/map_or_async': pathExperimentalAndHidden(`${MAYBE_DIR}/map_or_async`),
    'maybe/map_or_else': pathExperimentalAndHidden(`${MAYBE_DIR}/map_or_else`),
    'maybe/map_or_else_async': pathExperimentalAndHidden(`${MAYBE_DIR}/map_or_else_async`),
    'maybe/maybe': pathExperimentalAndHidden(`${MAYBE_DIR}/maybe`),
    'maybe/namespace': pathExperimentalAndHidden(`${MAYBE_DIR}/namespace`),
    'maybe/ok_or': pathExperimentalAndHidden(`${MAYBE_DIR}/ok_or`),
    'maybe/ok_or_else': pathExperimentalAndHidden(`${MAYBE_DIR}/ok_or_else`),
    'maybe/ok_or_else_async': pathExperimentalAndHidden(`${MAYBE_DIR}/ok_or_else_async`),
    'maybe/or': pathExperimentalAndHidden(`${MAYBE_DIR}/or`),
    'maybe/or_else': pathExperimentalAndHidden(`${MAYBE_DIR}/or_else`),
    'maybe/or_else_async': pathExperimentalAndHidden(`${MAYBE_DIR}/or_else_async`),
    'maybe/to_nullable': pathExperimentalAndHidden(`${MAYBE_DIR}/to_nullable`),
    'maybe/to_plain_result': pathExperimentalAndHidden(`${MAYBE_DIR}/to_plain_result`),
    'maybe/to_undefinable': pathExperimentalAndHidden(`${MAYBE_DIR}/to_undefinable`),
    'maybe/unwrap_or': pathExperimentalAndHidden(`${MAYBE_DIR}/unwrap_or`),
    'maybe/unwrap_or_else': pathExperimentalAndHidden(`${MAYBE_DIR}/unwrap_or_else`),
    'maybe/unwrap_or_else_async': pathExperimentalAndHidden(`${MAYBE_DIR}/unwrap_or_else_async`),
    'maybe/xor': pathExperimentalAndHidden(`${MAYBE_DIR}/xor`),
    'maybe/zip': pathExperimentalAndHidden(`${MAYBE_DIR}/zip`),
    'maybe/zip_with': pathExperimentalAndHidden(`${MAYBE_DIR}/zip_with`),
    'maybe/zip_with_async': pathExperimentalAndHidden(`${MAYBE_DIR}/zip_with_async`),

    'nullable': pathExperimentalAndHidden(`${NULLABLE_DIR}/index`),
    'nullable/and': pathExperimentalAndHidden(`${NULLABLE_DIR}/and`),
    'nullable/and_then': pathExperimentalAndHidden(`${NULLABLE_DIR}/and_then`),
    'nullable/and_then_async': pathExperimentalAndHidden(`${NULLABLE_DIR}/and_then_async`),
    'nullable/filter': pathExperimentalAndHidden(`${NULLABLE_DIR}/filter`),
    'nullable/filter_async': pathExperimentalAndHidden(`${NULLABLE_DIR}/filter_async`),
    'nullable/inspect': pathExperimentalAndHidden(`${NULLABLE_DIR}/inspect`),
    'nullable/map': pathExperimentalAndHidden(`${NULLABLE_DIR}/map`),
    'nullable/map_async': pathExperimentalAndHidden(`${NULLABLE_DIR}/map_async`),
    'nullable/map_or': pathExperimentalAndHidden(`${NULLABLE_DIR}/map_or`),
    'nullable/map_or_async': pathExperimentalAndHidden(`${NULLABLE_DIR}/map_or_async`),
    'nullable/map_or_else': pathExperimentalAndHidden(`${NULLABLE_DIR}/map_or_else`),
    'nullable/map_or_else_async': pathExperimentalAndHidden(`${NULLABLE_DIR}/map_or_else_async`),
    'nullable/namespace': pathExperimentalAndHidden(`${NULLABLE_DIR}/namespace`),
    'nullable/nullable': pathExperimentalAndHidden(`${NULLABLE_DIR}/nullable`),
    'nullable/ok_or': pathExperimentalAndHidden(`${NULLABLE_DIR}/ok_or`),
    'nullable/ok_or_else': pathExperimentalAndHidden(`${NULLABLE_DIR}/ok_or_else`),
    'nullable/ok_or_else_async': pathExperimentalAndHidden(`${NULLABLE_DIR}/ok_or_else_async`),
    'nullable/or': pathExperimentalAndHidden(`${NULLABLE_DIR}/or`),
    'nullable/or_else': pathExperimentalAndHidden(`${NULLABLE_DIR}/or_else`),
    'nullable/or_else_async': pathExperimentalAndHidden(`${NULLABLE_DIR}/or_else_async`),
    'nullable/to_plain_result': pathExperimentalAndHidden(`${NULLABLE_DIR}/to_plain_result`),
    'nullable/to_undefinable': pathExperimentalAndHidden(`${NULLABLE_DIR}/to_undefinable`),
    'nullable/unwrap_or': pathExperimentalAndHidden(`${NULLABLE_DIR}/unwrap_or`),
    'nullable/unwrap_or_else': pathExperimentalAndHidden(`${NULLABLE_DIR}/unwrap_or_else`),
    'nullable/unwrap_or_else_async': pathExperimentalAndHidden(
        `${NULLABLE_DIR}/unwrap_or_else_async`,
    ),
    'nullable/xor': pathExperimentalAndHidden(`${NULLABLE_DIR}/xor`),
    'nullable/zip': pathExperimentalAndHidden(`${NULLABLE_DIR}/zip`),
    'nullable/zip_with': pathExperimentalAndHidden(`${NULLABLE_DIR}/zip_with`),
    'nullable/zip_with_async': pathExperimentalAndHidden(`${NULLABLE_DIR}/zip_with_async`),

    'plain_option': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/index`),
    'plain_option/and': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/and`),
    'plain_option/and_then': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/and_then`),
    'plain_option/and_then_async': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/and_then_async`),
    'plain_option/as_mut': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/as_mut`),
    'plain_option/drop': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/drop`),
    'plain_option/equal': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/equal`),
    'plain_option/filter': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/filter`),
    'plain_option/flatten': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/flatten`),
    'plain_option/from_result': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/from_result`),
    'plain_option/inspect': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/inspect`),
    'plain_option/map': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/map`),
    'plain_option/map_async': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/map_async`),
    'plain_option/map_or': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/map_or`),
    'plain_option/map_or_async': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/map_or_async`),
    'plain_option/map_or_else': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/map_or_else`),
    'plain_option/map_or_else_async': pathExperimentalAndHidden(
        `${PLAIN_OPTION_DIR}/map_or_else_async`,
    ),
    'plain_option/namespace': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/namespace`),
    'plain_option/ok_or': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/ok_or`),
    'plain_option/ok_or_else': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/ok_or_else`),
    'plain_option/option': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/option`),
    'plain_option/or': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/or`),
    'plain_option/or_else': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/or_else`),
    'plain_option/or_else_async': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/or_else_async`),
    'plain_option/to_nullable': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/to_nullable`),
    'plain_option/to_undefinable': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/to_undefinable`),
    'plain_option/transpose': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/transpose`),
    'plain_option/unwrap_or': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/unwrap_or`),
    'plain_option/unwrap_or_else': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/unwrap_or_else`),
    'plain_option/unwrap_or_else_async': pathExperimentalAndHidden(
        `${PLAIN_OPTION_DIR}/unwrap_or_else_async`,
    ),
    'plain_option/xor': pathExperimentalAndHidden(`${PLAIN_OPTION_DIR}/xor`),

    'plain_result': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/index`),
    'plain_result/and': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/and`),
    'plain_result/and_then': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/and_then`),
    'plain_result/and_then_async': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/and_then_async`),
    'plain_result/as_mut': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/as_mut`),
    'plain_result/drop': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/drop`),
    'plain_result/equal': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/equal`),
    'plain_result/flatten': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/flatten`),
    'plain_result/from_promise_settled_result': pathExperimentalAndHidden(
        'plain_result/from_promise_settled_result',
    ),
    'plain_result/inspect': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/inspect`),
    'plain_result/is_err_and': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/is_err_and`),
    'plain_result/is_ok_and': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/is_ok_and`),
    'plain_result/map': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/map`),
    'plain_result/map_async': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/map_async`),
    'plain_result/map_err': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/map_err`),
    'plain_result/map_err_async': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/map_err_async`),
    'plain_result/map_or': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/map_or`),
    'plain_result/map_or_async': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/map_or_async`),
    'plain_result/map_or_else': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/map_or_else`),
    'plain_result/map_or_else_async': pathExperimentalAndHidden(
        `${PLAIN_RESULT_DIR}/map_or_else_async`,
    ),
    'plain_result/namespace': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/namespace`),
    'plain_result/or': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/or`),
    'plain_result/or_else': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/or_else`),
    'plain_result/or_else_async': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/or_else_async`),
    'plain_result/result': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/result`),
    'plain_result/to_nullable': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/to_nullable`),
    'plain_result/to_undefinable': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/to_undefinable`),
    'plain_result/transpose': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/transpose`),
    'plain_result/try_catch': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/try_catch`),
    'plain_result/try_catch_async': pathExperimentalAndHidden(
        `${PLAIN_RESULT_DIR}/try_catch_async`,
    ),
    'plain_result/unwrap_or': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/unwrap_or`),
    'plain_result/unwrap_or_else': pathExperimentalAndHidden(`${PLAIN_RESULT_DIR}/unwrap_or_else`),
    'plain_result/unwrap_or_else_async': pathExperimentalAndHidden(
        `${PLAIN_RESULT_DIR}/unwrap_or_else_async`,
    ),
    'plain_result/unwrap_or_throw_error': pathExperimentalAndHidden(
        `${PLAIN_RESULT_DIR}/unwrap_or_throw_error`,
    ),

    'undefinable': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/index`),
    'undefinable/and': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/and`),
    'undefinable/and_then': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/and_then`),
    'undefinable/and_then_async': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/and_then_async`),
    'undefinable/filter': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/filter`),
    'undefinable/filter_async': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/filter_async`),
    'undefinable/inspect': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/inspect`),
    'undefinable/map': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/map`),
    'undefinable/map_async': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/map_async`),
    'undefinable/map_or': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/map_or`),
    'undefinable/map_or_async': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/map_or_async`),
    'undefinable/map_or_else': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/map_or_else`),
    'undefinable/map_or_else_async': pathExperimentalAndHidden(
        `${UNDEFINABLE_DIR}/map_or_else_async`,
    ),
    'undefinable/namespace': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/namespace`),
    'undefinable/ok_or': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/ok_or`),
    'undefinable/ok_or_else': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/ok_or_else`),
    'undefinable/ok_or_else_async': pathExperimentalAndHidden(
        `${UNDEFINABLE_DIR}/ok_or_else_async`,
    ),
    'undefinable/or': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/or`),
    'undefinable/or_else': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/or_else`),
    'undefinable/or_else_async': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/or_else_async`),
    'undefinable/to_nullable': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/to_nullable`),
    'undefinable/to_plain_result': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/to_plain_result`),
    'undefinable/undefinable': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/undefinable`),
    'undefinable/unwrap_or': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/unwrap_or`),
    'undefinable/unwrap_or_else': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/unwrap_or_else`),
    'undefinable/unwrap_or_else_async': pathExperimentalAndHidden(
        `${UNDEFINABLE_DIR}/unwrap_or_else_async`,
    ),
    'undefinable/xor': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/xor`),
    'undefinable/zip': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/zip`),
    'undefinable/zip_with': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/zip_with`),
    'undefinable/zip_with_async': pathExperimentalAndHidden(`${UNDEFINABLE_DIR}/zip_with_async`),
});
