/* eslint sort-keys: ["error", "asc", { caseSensitive: true }] */

const DEFAULT_API_DESCRIPTOR = Object.freeze({
    actualFilePath: null,
    shouldHideInDoc: false,
    // eslint-disable-next-line sort-keys
    createCompat: true,
});

function pathRedirectionTo(actualFilePath) {
    return Object.freeze({
        actualFilePath,
        shouldHideInDoc: DEFAULT_API_DESCRIPTOR.shouldHideInDoc,
        // eslint-disable-next-line sort-keys
        createCompat: DEFAULT_API_DESCRIPTOR.createCompat,
    });
}

function pathRedirectionForLegacy(actualFilePath) {
    return Object.freeze({
        actualFilePath,
        shouldHideInDoc: true,
        // eslint-disable-next-line sort-keys
        createCompat: DEFAULT_API_DESCRIPTOR.createCompat,
    });
}

function pathRedirectionForRoot(actualFilePath) {
    return Object.freeze({
        actualFilePath,
        shouldHideInDoc: true,
        // eslint-disable-next-line sort-keys
        createCompat: false,
    });
}

export const apiTable = Object.freeze({
    '.': pathRedirectionForRoot('index'),

    'ClassicOption': pathRedirectionForLegacy('ClassicOption/index'),
    'ClassicResult': pathRedirectionForLegacy('ClassicResult/index'),

    'Maybe': pathRedirectionTo('Maybe/index'),
    'Maybe/Maybe': DEFAULT_API_DESCRIPTOR,
    'Maybe/and': DEFAULT_API_DESCRIPTOR,
    'Maybe/andThen': DEFAULT_API_DESCRIPTOR,
    'Maybe/andThenAsync': DEFAULT_API_DESCRIPTOR,
    'Maybe/compat/v33': DEFAULT_API_DESCRIPTOR,
    'Maybe/expect': DEFAULT_API_DESCRIPTOR,
    'Maybe/inspect': DEFAULT_API_DESCRIPTOR,
    'Maybe/map': DEFAULT_API_DESCRIPTOR,
    'Maybe/mapAsync': DEFAULT_API_DESCRIPTOR,
    'Maybe/mapOr': DEFAULT_API_DESCRIPTOR,
    'Maybe/mapOrAsync': DEFAULT_API_DESCRIPTOR,
    'Maybe/mapOrElse': DEFAULT_API_DESCRIPTOR,
    'Maybe/mapOrElseAsync': DEFAULT_API_DESCRIPTOR,
    'Maybe/namespace': DEFAULT_API_DESCRIPTOR,
    'Maybe/okOr': DEFAULT_API_DESCRIPTOR,
    'Maybe/okOrElse': DEFAULT_API_DESCRIPTOR,
    'Maybe/or': DEFAULT_API_DESCRIPTOR,
    'Maybe/orElse': DEFAULT_API_DESCRIPTOR,
    'Maybe/orElseAsync': DEFAULT_API_DESCRIPTOR,
    'Maybe/toNullable': DEFAULT_API_DESCRIPTOR,
    'Maybe/toPlainResult': DEFAULT_API_DESCRIPTOR,
    'Maybe/toUndefinable': DEFAULT_API_DESCRIPTOR,
    'Maybe/unwrap': DEFAULT_API_DESCRIPTOR,
    'Maybe/unwrapOr': DEFAULT_API_DESCRIPTOR,
    'Maybe/unwrapOrElse': DEFAULT_API_DESCRIPTOR,
    'Maybe/unwrapOrElseAsync': DEFAULT_API_DESCRIPTOR,
    'Maybe/xor': DEFAULT_API_DESCRIPTOR,

    'Nullable': pathRedirectionTo('Nullable/index'),
    'Nullable/Nullable': DEFAULT_API_DESCRIPTOR,
    'Nullable/and': DEFAULT_API_DESCRIPTOR,
    'Nullable/andThen': DEFAULT_API_DESCRIPTOR,
    'Nullable/andThenAsync': DEFAULT_API_DESCRIPTOR,
    'Nullable/compat/v33': DEFAULT_API_DESCRIPTOR,
    'Nullable/expect': DEFAULT_API_DESCRIPTOR,
    'Nullable/inspect': DEFAULT_API_DESCRIPTOR,
    'Nullable/map': DEFAULT_API_DESCRIPTOR,
    'Nullable/mapAsync': DEFAULT_API_DESCRIPTOR,
    'Nullable/mapOr': DEFAULT_API_DESCRIPTOR,
    'Nullable/mapOrAsync': DEFAULT_API_DESCRIPTOR,
    'Nullable/mapOrElse': DEFAULT_API_DESCRIPTOR,
    'Nullable/mapOrElseAsync': DEFAULT_API_DESCRIPTOR,
    'Nullable/namespace': DEFAULT_API_DESCRIPTOR,
    'Nullable/okOr': DEFAULT_API_DESCRIPTOR,
    'Nullable/okOrElse': DEFAULT_API_DESCRIPTOR,
    'Nullable/or': DEFAULT_API_DESCRIPTOR,
    'Nullable/orElse': DEFAULT_API_DESCRIPTOR,
    'Nullable/orElseAsync': DEFAULT_API_DESCRIPTOR,
    'Nullable/toPlainResult': DEFAULT_API_DESCRIPTOR,
    'Nullable/toUndefinable': DEFAULT_API_DESCRIPTOR,
    'Nullable/unwrap': DEFAULT_API_DESCRIPTOR,
    'Nullable/unwrapOr': DEFAULT_API_DESCRIPTOR,
    'Nullable/unwrapOrElse': DEFAULT_API_DESCRIPTOR,
    'Nullable/unwrapOrElseAsync': DEFAULT_API_DESCRIPTOR,
    'Nullable/xor': DEFAULT_API_DESCRIPTOR,

    'PlainOption': pathRedirectionTo('PlainOption/index'),
    'PlainOption/Option': DEFAULT_API_DESCRIPTOR,
    'PlainOption/and': DEFAULT_API_DESCRIPTOR,
    'PlainOption/andThen': DEFAULT_API_DESCRIPTOR,
    'PlainOption/andThenAsync': DEFAULT_API_DESCRIPTOR,
    'PlainOption/asMut': DEFAULT_API_DESCRIPTOR,
    'PlainOption/compat/v33': DEFAULT_API_DESCRIPTOR,
    'PlainOption/drop': DEFAULT_API_DESCRIPTOR,
    'PlainOption/equal': DEFAULT_API_DESCRIPTOR,
    'PlainOption/expect': DEFAULT_API_DESCRIPTOR,
    'PlainOption/filter': DEFAULT_API_DESCRIPTOR,
    'PlainOption/flatten': DEFAULT_API_DESCRIPTOR,
    'PlainOption/inspect': DEFAULT_API_DESCRIPTOR,
    'PlainOption/map': DEFAULT_API_DESCRIPTOR,
    'PlainOption/mapAsync': DEFAULT_API_DESCRIPTOR,
    'PlainOption/mapOr': DEFAULT_API_DESCRIPTOR,
    'PlainOption/mapOrAsync': DEFAULT_API_DESCRIPTOR,
    'PlainOption/mapOrElse': DEFAULT_API_DESCRIPTOR,
    'PlainOption/mapOrElseAsync': DEFAULT_API_DESCRIPTOR,
    'PlainOption/namespace': DEFAULT_API_DESCRIPTOR,
    'PlainOption/okOr': DEFAULT_API_DESCRIPTOR,
    'PlainOption/okOrElse': DEFAULT_API_DESCRIPTOR,
    'PlainOption/or': DEFAULT_API_DESCRIPTOR,
    'PlainOption/orElse': DEFAULT_API_DESCRIPTOR,
    'PlainOption/orElseAsync': DEFAULT_API_DESCRIPTOR,
    'PlainOption/toNullable': DEFAULT_API_DESCRIPTOR,
    'PlainOption/toUndefinable': DEFAULT_API_DESCRIPTOR,
    'PlainOption/transpose': DEFAULT_API_DESCRIPTOR,
    'PlainOption/unwrap': DEFAULT_API_DESCRIPTOR,
    'PlainOption/unwrapOr': DEFAULT_API_DESCRIPTOR,
    'PlainOption/unwrapOrElse': DEFAULT_API_DESCRIPTOR,
    'PlainOption/unwrapOrElseAsync': DEFAULT_API_DESCRIPTOR,
    'PlainOption/xor': DEFAULT_API_DESCRIPTOR,

    'PlainResult': pathRedirectionTo('PlainResult/index'),
    'PlainResult/Result': DEFAULT_API_DESCRIPTOR,
    'PlainResult/and': DEFAULT_API_DESCRIPTOR,
    'PlainResult/andThen': DEFAULT_API_DESCRIPTOR,
    'PlainResult/andThenAsync': DEFAULT_API_DESCRIPTOR,
    'PlainResult/asMut': DEFAULT_API_DESCRIPTOR,
    'PlainResult/compat/v33': DEFAULT_API_DESCRIPTOR,
    'PlainResult/drop': DEFAULT_API_DESCRIPTOR,
    'PlainResult/equal': DEFAULT_API_DESCRIPTOR,
    'PlainResult/expect': DEFAULT_API_DESCRIPTOR,
    'PlainResult/flatten': DEFAULT_API_DESCRIPTOR,
    'PlainResult/fromPromiseSettledResult': DEFAULT_API_DESCRIPTOR,
    'PlainResult/inspect': DEFAULT_API_DESCRIPTOR,
    'PlainResult/map': DEFAULT_API_DESCRIPTOR,
    'PlainResult/mapAsync': DEFAULT_API_DESCRIPTOR,
    'PlainResult/mapErr': DEFAULT_API_DESCRIPTOR,
    'PlainResult/mapErrAsync': DEFAULT_API_DESCRIPTOR,
    'PlainResult/mapOr': DEFAULT_API_DESCRIPTOR,
    'PlainResult/mapOrAsync': DEFAULT_API_DESCRIPTOR,
    'PlainResult/mapOrElse': DEFAULT_API_DESCRIPTOR,
    'PlainResult/mapOrElseAsync': DEFAULT_API_DESCRIPTOR,
    'PlainResult/namespace': DEFAULT_API_DESCRIPTOR,
    'PlainResult/or': DEFAULT_API_DESCRIPTOR,
    'PlainResult/orElse': DEFAULT_API_DESCRIPTOR,
    'PlainResult/orElseAsync': DEFAULT_API_DESCRIPTOR,
    'PlainResult/toNullable': DEFAULT_API_DESCRIPTOR,
    'PlainResult/toOption': DEFAULT_API_DESCRIPTOR,
    'PlainResult/toUndefinable': DEFAULT_API_DESCRIPTOR,
    'PlainResult/transpose': DEFAULT_API_DESCRIPTOR,
    'PlainResult/tryCatch': DEFAULT_API_DESCRIPTOR,
    'PlainResult/tryCatchAsync': DEFAULT_API_DESCRIPTOR,
    'PlainResult/unwrap': DEFAULT_API_DESCRIPTOR,
    'PlainResult/unwrapOr': DEFAULT_API_DESCRIPTOR,
    'PlainResult/unwrapOrElse': DEFAULT_API_DESCRIPTOR,
    'PlainResult/unwrapOrElseAsync': DEFAULT_API_DESCRIPTOR,
    'PlainResult/unwrapOrThrowError': DEFAULT_API_DESCRIPTOR,

    'Undefinable': pathRedirectionTo('Undefinable/index'),
    'Undefinable/Undefinable': DEFAULT_API_DESCRIPTOR,
    'Undefinable/and': DEFAULT_API_DESCRIPTOR,
    'Undefinable/andThen': DEFAULT_API_DESCRIPTOR,
    'Undefinable/andThenAsync': DEFAULT_API_DESCRIPTOR,
    'Undefinable/compat/v33': DEFAULT_API_DESCRIPTOR,
    'Undefinable/expect': DEFAULT_API_DESCRIPTOR,
    'Undefinable/inspect': DEFAULT_API_DESCRIPTOR,
    'Undefinable/map': DEFAULT_API_DESCRIPTOR,
    'Undefinable/mapAsync': DEFAULT_API_DESCRIPTOR,
    'Undefinable/mapOr': DEFAULT_API_DESCRIPTOR,
    'Undefinable/mapOrAsync': DEFAULT_API_DESCRIPTOR,
    'Undefinable/mapOrElse': DEFAULT_API_DESCRIPTOR,
    'Undefinable/mapOrElseAsync': DEFAULT_API_DESCRIPTOR,
    'Undefinable/namespace': DEFAULT_API_DESCRIPTOR,
    'Undefinable/okOr': DEFAULT_API_DESCRIPTOR,
    'Undefinable/okOrElse': DEFAULT_API_DESCRIPTOR,
    'Undefinable/or': DEFAULT_API_DESCRIPTOR,
    'Undefinable/orElse': DEFAULT_API_DESCRIPTOR,
    'Undefinable/orElseAsync': DEFAULT_API_DESCRIPTOR,
    'Undefinable/toNullable': DEFAULT_API_DESCRIPTOR,
    'Undefinable/toPlainResult': DEFAULT_API_DESCRIPTOR,
    'Undefinable/unwrap': DEFAULT_API_DESCRIPTOR,
    'Undefinable/unwrapOr': DEFAULT_API_DESCRIPTOR,
    'Undefinable/unwrapOrElse': DEFAULT_API_DESCRIPTOR,
    'Undefinable/unwrapOrElseAsync': DEFAULT_API_DESCRIPTOR,
    'Undefinable/xor': DEFAULT_API_DESCRIPTOR,
});

