const ERR_MSG_MUST_RETURN_PROMISE = ' must return Promise';
const ERR_MSG_MUST_NOT_RETURN = ' must not return ';

const TRANSFORM_FUNCTION_NAME = '`transformer`';
const RECOVERY_FUNCTION_NAME = '`recoverer`';
const DEFAULT_ARG_NAME = '`def`';

export const ERR_MSG_SELECTOR_MUST_NOT_RETURN = '`selector`' + ERR_MSG_MUST_NOT_RETURN;
export const ERR_MSG_CALLED_WITH = 'called with ';
export const ERR_MSG_DEF_MUST_NOT_BE = DEFAULT_ARG_NAME + ' must not be ';
export const ERR_MSG_DEF_MUST_NOT_RETURN = DEFAULT_ARG_NAME + ERR_MSG_MUST_NOT_RETURN;

export const ERR_MSG_TRANSFORMER_MUST_RETURN_PROMISE =
    TRANSFORM_FUNCTION_NAME + ERR_MSG_MUST_RETURN_PROMISE;

export const ERR_MSG_RECOVERER_MUST_RETURN_PROMISE =
    RECOVERY_FUNCTION_NAME + ERR_MSG_MUST_RETURN_PROMISE;
