name: CI workflow template
# we need separate CI workflow template to achieve that a CI
# for each of PRs cancellable and one for default branch should run on every commits
# because the runner will use `concurrency.group` in the callee worfklow which is
# configured as cancellable if we don't set `concurrency.group` to caller workflow.
on:
    workflow_call:

permissions:
    contents: read

jobs:
    warmup_dependency_cache:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version:
                    # We think that we don't have to specify all versions which we'd like to test
                    # because almost npm packages cares about platform but don't care about node's version.
                    - 24

        steps:
            - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
            - uses: ./.github/actions/prepare_ci
              with:
                  node-version: ${{ matrix.node-version }}

    format_check:
        needs: [warmup_dependency_cache]
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version:
                    - 24

        steps:
            - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
            - uses: ./.github/actions/prepare_ci
              with:
                  node-version: ${{ matrix.node-version }}
            - run: make format_check -j
              env:
                  CI: true

    lint:
        needs: [warmup_dependency_cache]
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version:
                    - 24

        steps:
            - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
            - uses: ./.github/actions/prepare_ci
              with:
                  node-version: ${{ matrix.node-version }}
            - run: make lint -j
              env:
                  CI: true

    build:
        needs: [warmup_dependency_cache]
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version:
                    - 24

        steps:
            - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
            - uses: ./.github/actions/prepare_ci
              with:
                  node-version: ${{ matrix.node-version }}
            - run: make build -j
              env:
                  CI: true

    unittest:
        needs: [warmup_dependency_cache]
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version:
                    - 24

        steps:
            - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
            - uses: ./.github/actions/prepare_ci
              with:
                  node-version: ${{ matrix.node-version }}
            - run: make test_unittest -j
              env:
                  CI: true

    api_typing_test:
        needs: [warmup_dependency_cache]
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version:
                    - 24

        steps:
            - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
            - uses: ./.github/actions/prepare_ci
              with:
                  node-version: ${{ matrix.node-version }}
            - run: make test_api_typing -j
              env:
                  CI: true

    test_package_json_exports_field_format:
        needs: [warmup_dependency_cache]
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version:
                    - 24
        steps:
            - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
            - uses: ./.github/actions/prepare_ci
              with:
                  node-version: ${{ matrix.node-version }}
            - run: make test_package_json_exports_field_format -j
              env:
                  CI: true

    test_import_types:
        needs: [warmup_dependency_cache]
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version:
                    - 24
        steps:
            - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
            - uses: ./.github/actions/prepare_ci
              with:
                  node-version: ${{ matrix.node-version }}
            - run: make test_import_types -j
              env:
                  CI: true

    test_distribution_contain_all:
        needs: [warmup_dependency_cache]
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version:
                    - 24

        steps:
            - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
            - uses: ./.github/actions/prepare_ci
              with:
                  node-version: ${{ matrix.node-version }}
            - run: make test_distribution_contain_all -j
              env:
                  CI: true

    sentinel:
        needs:
            - format_check
            - build
            - lint
            - unittest
            - test_package_json_exports_field_format
            - test_import_types
            - test_distribution_contain_all
        runs-on: ubuntu-latest
        if: ${{ always() }}
        steps:
            - name: Check whether required jobs are successful
              if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
              # Fail this job
              run: exit 1
