name: publish to npm
on:
    release:
        types: [released]
permissions: {}

jobs:
    build:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            # This is required for provenance
            # see https://docs.npmjs.com/generating-provenance-statements
            id-token: write # OIDC

        timeout-minutes: 10 # This value is just by feeling.

        steps:
            - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
              with:
                  persist-credentials: false
            - uses: ./.github/actions/prepare_ci
              with:
                  node-version: 24
            - run: pnpm ci
            - run: make clean
            - run: make prepublish -j
            - run: make publish -j
